### ISSUE TITLE
Test results

### ISSUE THREAD

**Issue by kyr0** [PCemOnMac/PCemV17macOS#1]
Catalina:
- compilation works flawlessy
- resulting binary executes MS DOS 6.22
- loads CD driver
- I can play Jazzjack rabbit

-> Performance is better than in V16 -- no more micro lags in sound/video playback
-> But OpenGL 3 rendering backend NOT available
-> Software rendering and OpenGL 2 works

**Comment by almeath** [comment]
I have just updated the source code and I believe Open GL 3.0 should now be selectable. Can you please confirm?

**Comment by kyr0** [comment]
Works great

**Comment by kyr0** [comment]
Guess we can close this?

**Comment by almeath** [comment]
I agree
