### ISSUE TITLE
ARM64 Silicon, runs very well but toolbar menu is not present

### ISSUE THREAD

**Issue by aminta** [PCemOnMac/PCemV17macOS#20]
I'm on MacBook 13" M1 8+8 core 16Gb, compiled from last source.

Toolbar in Windows:
<img width="637" alt="Schermata 2021-05-20 alle 22 12 24" src="https://user-images.githubusercontent.com/1983688/119043014-e01c3c80-b9b8-11eb-98a5-9ff290316603.png">

No toolbar in Mac:
<img width="641" alt="Schermata 2021-05-20 alle 22 16 30" src="https://user-images.githubusercontent.com/1983688/119043157-093ccd00-b9b9-11eb-82fa-e91dab1ba8d1.png">

**Comment by Shambler2** [comment]
Hi!

I was also confused by this at first, however this is the default behaviour for both this port and the Linux port (that is part of mainline PCEM) - you can access the menus by right clicking on the main window when the mouse is not being captured

**Comment by aminta** [comment]
Thanks!

**Comment by brunocastello** [comment]
@aminta does PCem run well on your M1 ? Good enough for a Pentium II with Voodoo II ?
