### ISSUE TITLE
No ROMs detected on Mac Mini M1

### ISSUE THREAD

**Issue by kyods** [PCemOnMac/PCemV17macOS#23]
I managed to compile and PCem successfully after changing the path from /usr/local/Cellar to /opt/homebrew/Cellar, however when I run the executable, I get the "PCem fatal error: No ROMs present popup", even though I have sis496-1.awa ROM sitting in the roms/sis496 folder. Additionally in the terminal window I see the following messages - I'm not sure if they are relevant:
Menu item not found: 1403
Menu item not found: 1404
What am I doing wrong?

**Comment by kyods** [comment]
Nevermind, figured it out. Solution for other noobs baffled just as me: ROMs go into ~/Library/Application Support/PCEm/roms

**Comment by almeath** [comment]
In earlier builds the roms would go in the user's Documents folder, but it was considered more standard for macOS app behavior if it went in Application Support instead, so I agreed to the change.

**Comment by brunocastello** [comment]
Or if you're just like me, using an external hard disk to store virtual machines, backups and other stuff, you can just symlink the application support's roms folder to one in your other place. Worked for me in the past.
